workflows:
  ios-workflow:
    name: iOS workflow
    environment:
     
      xcode: 12.1
      node: 14.15.0
      npm: 6.14.8
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm ci
          cvm install 10.0.0
          cvm use 10.0.0
          npm install -g ionic
          ionic info   
      - name: Setup iOS
        script: |
          ionic cordova platform remove ios --nosave
          ionic cordova platform add ios --confirm --no-interactive --noresources --save  
      
      - name: Build iOS
        script: |
         
          ionic cordova build ios --prod
    artifacts:
      - /Users/builder/clone/platforms/ios/build/device/*.ipa
      - /tmp/xcodebuild_logs/*.lo